name: Build

on:
  push:
    branches:
      - main  # Adjust this according to your main branch name
  pull_request:
    branches:
      - main  # Adjust this according to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to /client
        run: cd client

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
